

services:
    appvet:
        build:
            context: ./vscodepruebavet
            dockerfile: Dockerfile
        mem_limit: 512m
        ports:
            - "8080:8080"
        environment:
            - SPRING_DATASOURCE_URL=jdbc:mysql://prueba_jpa:3306/prueba_jpa?createDatabaseIfNotExist=true&serverTimezone=UTC
            - SPRING_DATASOURCE_USERNAME=root
            - SPRING_DATASOURCE_PASSWORD=root

        restart: always
        depends_on:
            prueba_jpa:
                condition: service_healthy
    prueba_jpa:        
        image: mysql:8.0.33
        ports:
            - "3307:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=prueba_jpa
        restart: always
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 10s
            retries: 3
